# Default values for aps.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alfresco/process-services
  tag: 1.9.0.1
  pullPolicy: IfNotPresent

nameOverride: "aps"
fullnameOverride: "aps"

service:
  name: aps
  type: ClusterIP
  port: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.path: /activiti-app
    # fabric8.io/ingress.name: aps

ingress:
  name: aps
  enabled: false
  annotations:
     kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /activiti-app
  hosts:
    - aps.activiti-cloud.emailbpm.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
